### PR TITLE
Bringing my forked repo's master up-to-date with Tribal's master branch

### PR DESCRIPTION
**Pull request by ramshamushtaq**

### CODE REVIEW

**Comment by jhogan4288** [comment]
From the PR description, it sounds like you want to update the `master` branch on your forked repo?  

The way to do this is from your local machine:
`git checkout master`
`git pull --rebase upstream master` (this will update your local repo w/the shared `master`)
`git push origin master` (this will update your forked GitHub repo with your now-up-to-date local `master`)

The PR, in contrast, is initiating a process to update the *shared* `master` with changes from your forked `master`, which I think is the opposite of what you want.

I'll leave this open for the moment until you confirm :-)

**Comment by jhogan4288** [comment]
Also, assuming you're doing your Spotify coding on a feature branch, you'll also want to do:

`git checkout [branch-name]`
`git pull --rebase upstream master`

This will rebase your feature branch onto the latest code from `The-Justice-League/master`.

**Comment by ramshamushtaq** [comment]
Yes you’re correct. I went deep into the pits of git hell today. I’ll do this soon. Currently working on the spotifySearch branch. Will make sure to rebase first :)

**Comment by jhogan4288** [comment]
cool.  let me know if you want a hand w/it tomorrow.  I'll close the PR

**Pull request closed without merging**
